# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.100.11"
  config.vm.network :forwarded_port, guest: 9600, host: 9600
  config.vm.network :forwarded_port, guest: 9700, host: 9700

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "logstash"
    vb.memory = "2048"
    vb.cpus = "2"
  end
end 
